services:

  mail_service:
    container_name: mail_service
    build: .
    ports:
      - "9876:9876"
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - local-kafka

networks:
  local-kafka:
    name: local-kafka
    external: true
